FROM php:8.2-cli

WORKDIR /var/www

RUN apt-get update && \
    apt-get install libzip-dev -y && \
    docker-php-ext-install zip

RUN apt-get install nodejs -y

RUN apt-get install npm -y

RUN apt-get install git -y

RUN git clone https://github.com/jhonatasFelipe/robots.git robots

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');"

RUN mv composer.phar /var/www/robots

WORKDIR /var/www/robots

RUN php composer.phar install 

RUN npm install

ENTRYPOINT [ "php","artisan","serve" ]
CMD [ "--host=0.0.0.0" ]
